### ISSUE TITLE
Test main in static_transform_broadcaster_program.cpp

### ISSUE THREAD

**Issue by wasowski** [wasowski/geometry2_167#1]
@gavanderhoorn @ChrisTimperley 

This is a bit long, but I believe that we are very close to closing (!) the first L3 bug. I am sorry to bother you but I figured that I am running in circles.

The objective in this fork is to add a test case for the main function of `static_transform_broadcaster_program.cpp` in` tf2_ros/src`. We need to call this program (unfortunately a ROS node) with 9 arguments and cause a violation of the assertion that I inserted there in line 73.

I have ruled against writing a gtest for this, as I don't think we can have two main functions in a program.  I don't know Google test, so feel free to correct me here. I went for python instead. Find the test at: https://github.com/wasowski/geometry2_167/blob/69c959e371eaf00a25f6b4911769de551096b009/tf2_ros/test/bug_witness.py

NB. changes are in the `reproduction` branch.

I don't know how to properly invoke this C++ executable.  Some issues:
1. First it does not appear to be in the path. 
2. It is a ROS node, so I need to launch it properly, and I have no idea how to do it with respect to a test case.
3. I need to watch from this python test whether it crashed. 
4. I need to close it down gracefully (when? after some time?) if it did not -- the test should pass after I patch the C++ file with the bug fix.

I would really welcome help, in form of a discussion here, or in form of a patch.

I don't hope that you will test it yourself, but if you wanted then the directory `data/b4dc23c.L3/` in the bitbucket repo with bugs contains the setup to reproduce the situation.  It suffices to run:
```
docker build -t b4dc23c . && docker run -it b4dc23c ./test.sh
```
in that directory to run my test case.  Presently, the test case will just fail, because of the always failing assertion.   This assertion needs to be replaced.

If you want to try a different test, regenerate the patch `bug_witness.patch` and docker will pick it up at the next run. 

This fork contains only the development of this particular test (so a patch can be obtained by taking all commits from the forking point). 

Heeeelp!

PS. And huge thanks to both of you - at least for this bug the docker set up seems to shine.  In retrospect I did nothing (ah, some minor tweaks to add the patch, etc).  Everything was there for weeks now, made by you. I just needed to digest it, to understand that the problem is almost solved.

**Comment by wasowski** [comment]
@gavanderhoor

**Comment by wasowski** [comment]
@gavanderhoorn, I am almost there.  I am now running the test with:
```
catkin_make_isolated --pkg tf2_ros --make-args run_tests
```
(you gave it to me, but can't recall in which discussion :) ).

Is there a way to run a particular test? The above runs all the tests for a package.  Running a particular test would help the users to directly get to the bug, independently of other things failing, taking a long time, etc.

**Comment by gavanderhoorn** [comment]
There are a few options. Directly running `rostest` is one, although no often used. It is the most direct route though.

The two `catkin_make_isolated` invocations are also ok. They'll just build and run much more than just your single test.

There is a way to run just your specific test (see [How do I only run tests for only one package?](https://answers.ros.org/question/62583) fi), but I would need access to your files to be able to tell you exactly which target to use.

**Comment by gavanderhoorn** [comment]
> Also I still need a catkin_make_isolated that builds all the tests without running them otherwise (so that I can use rostests).

IIRC, this is needed as there is no easy way to make tests (transitivally) depend on all required packages, libraries and binaries. But it's been a while since I asked Dirk about this, so perhaps I'm mistaken.

**Comment by gavanderhoorn** [comment]
As to needing to use `catkin_make_isolated` for everything: what we probably could do is create two workspaces:

 - one with all the (transitive) dependencies of the package-under-test, but excluding the PUT
 - one with just the PUT, overlaying the first one

The first workspace would then need `catkin_make_isolated`, while the second should build with just `catkin_make`.

I can discuss this with @ChrisTimperley, it should not be too difficult, as `rosinstall_generator` explicitly supports this usecase, and workspace overlaying is a basic practice in ROS.

**Comment by gavanderhoorn** [comment]
Btw, see [Running rostest manually from the command-line](http://wiki.ros.org/rostest/Commandline) for usage.

Note that if you want to be nice, rename your `.launch` file to a `.test`.

**Comment by wasowski** [comment]
Thx. I renamed (although this requires extra setup in vim to get syntax highlighting again :( )

**Comment by wasowski** [comment]
I am still trying to get the last. Is there really no way to:
1. Fail a rostest launch based on failure of an optional node selectively (by raising the right signal, etc.)?
2. Avoid failing a rostest launch based on how a required node has quit? It seems to fail even if a required node exited gracefully?

Or is there some way to start a node from inside a python test or gtest (without the launch file) so as to explicitly test what was the return code?

(I am presently experimenting with launch-prefix to intercept results in a script, but this does not appear to be easy or particularly clean.)

**Comment by wasowski** [comment]
Renamed.  And the case is now tested (albeit not the simple insert-one-assertion approach that I anticipated originally). Case closed :)

(renaming to .test looses syntax highlighting in my vim setup - now I need another thing to procrastinate on)
